version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-lambda-bucket
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml