version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file template.yml --s3-bucket codepipeline-us-east-1-405541440213
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yml
    - outputSamTemplate.yaml